### PR TITLE
Added JsON parsing

### PR DESCRIPTION
**Pull request by MadTribe**

### CODE REVIEW

**Comment by jkzx** [comment]
When I pass the following json string as body I got error:

> {"device-id":"46820256-0ed7-4895-b2d4-6691a081b2a5","reading-time":1561104785,"reading":{"voltage-V":123,"current-A":5.6,"active-power-W":688.8,"accumulated-power-kWh":9999,"frequency-Hz":50,"power-factor":0.9}}

Error:

> {
>     "errorMessage": "Uncaught error in your 'create' handler",
>     "errorType": "SyntaxError",
>     "stackTrace": [
>         "SyntaxError: Unexpected token u in JSON at position 0",
>         "at JSON.parse (<anonymous>)",
>         "at create (/Users/kv/Workspace/cream-services/cream-services/.webpack/service/webpack:/create.js:4:21)",
>         "at /Users/kv/Workspace/cream-services/cream-services/node_modules/serverless-offline/src/index.js:1022:21",
>         "at new Promise (<anonymous>)",
>         "at handler (/Users/kv/Workspace/cream-services/cream-services/node_modules/serverless-offline/src/index.js:705:20)",
>         "at module.exports.internals.Manager.execute (/Users/kv/Workspace/cream-services/cream-services/node_modules/@hapi/hapi/lib/toolkit.js:41:33)",
>         "at Object.internals.handler (/Users/kv/Workspace/cream-services/cream-services/node_modules/@hapi/hapi/lib/handler.js:46:48)",
>         "at exports.execute (/Users/kv/Workspace/cream-services/cream-services/node_modules/@hapi/hapi/lib/handler.js:31:36)",
>         "at Request._lifecycle (/Users/kv/Workspace/cream-services/cream-services/node_modules/@hapi/hapi/lib/request.js:312:68)",
>         "at processTicksAndRejections (internal/process/task_queues.js:89:5)"
>     ],
>     "offlineInfo": "If you believe this is an issue with the plugin please submit it, thanks. https://github.com/dherault/serverless-offline/issues"
> }
>

**Comment by MadTribe** [comment]
@jkzx  can you add your postman request to this discussion? So I can try to reproduce the issue.

**Comment by jkzx** [comment]
@MadTribe here is the postman request
[debug.postman_collection.json.zip](https://github.com/mee-panyar-cream/cream-services/files/3345433/debug.postman_collection.json.zip)

**Comment by MadTribe** [comment]
@jkzx I see. Try this one, I think this is the correct url to use.

[CREAM-services.postman_collection.json.zip](https://github.com/mee-panyar-cream/cream-services/files/3346839/CREAM-services.postman_collection.json.zip)

**Pull request merged**
